name: Java CI dengan Gradle dan Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-java-docker:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Persiapkan JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Beri izin eksekusi untuk gradlew
      run: chmod +x gradlew

    - name: Bangun dengan Gradle
      run: ./gradlew build

    - name: Periksa direktori build/libs
      run: ls -R build/libs/

    - name: Persiapkan QEMU
      uses: docker/setup-qemu-action@v2

    - name: Persiapkan Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Bangun dan dorong
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: imam3543/wallpaper:latest
